(()=>{if(window.__priceWatcherLoaded)return;window.__priceWatcherLoaded=true;let mode="idle",hovered=null,highlight=null,panel=null,editingId=null,candidate=null;
chrome.runtime.onMessage.addListener(m=>{if(m.type==="START_PICKER")start(m.watchId||null)});
function start(watchId=null){cleanup();editingId=watchId;mode="picking";document.documentElement.classList.add("pw-picking");highlight=document.createElement("div");highlight.id="pw-highlight";document.body.append(highlight);showPickerPanel();document.addEventListener("mousemove",onMove,true);document.addEventListener("click",onPick,true);document.addEventListener("keydown",onKey,true)}
function showPickerPanel(){panel?.remove();panel=document.createElement("div");panel.id="pw-panel";panel.innerHTML=`<div class="pw-head"><span class="pw-step">1</span><div><strong>选择价格元素</strong><p>移动鼠标，高亮框会自动定位页面元素</p></div><button class="pw-close">×</button></div><div class="pw-tip"><span>操作提示</span>点击包含商品价格的最小区域，按 Esc 可退出</div>`;document.body.append(panel);panel.querySelector(".pw-close").onclick=cleanup}
function onMove(e){if(mode!=="picking"||panel?.contains(e.target)||e.target===highlight)return;hovered=e.target;const r=hovered.getBoundingClientRect();Object.assign(highlight.style,{left:`${r.left}px`,top:`${r.top}px`,width:`${r.width}px`,height:`${r.height}px`})}
function onPick(e){if(mode!=="picking"||!hovered||panel.contains(e.target))return;e.preventDefault();e.stopImmediatePropagation();const text=hovered.textContent.trim(),price=parsePrice(text);if(!Number.isFinite(price))return toast("没有识别到价格，请选择更精确的区域");candidate={selector:cssPath(hovered),text,price,currency:detectCurrency(text)};showConfirmation()}
function showConfirmation(){mode="confirming";document.documentElement.classList.remove("pw-picking");document.removeEventListener("mousemove",onMove,true);document.removeEventListener("click",onPick,true);highlight?.remove();highlight=null;panel.innerHTML=`<div class="pw-head"><span class="pw-step">2</span><div><strong>确认识别结果</strong><p>确认无误后设置提醒价格</p></div><button class="pw-close">×</button></div><div class="pw-result"><span>识别到的价格</span><b>${escapeHtml(candidate.currency)}${candidate.price.toLocaleString()}</b><small title="${escapeHtml(candidate.text)}">${escapeHtml(candidate.text.slice(0,90))}</small></div><label class="pw-field"><span>商品名称</span><input id="pw-title" value="${escapeHtml(document.title.slice(0,100))}"></label><label class="pw-field"><span>目标价格（价格 ≤ 目标价时提醒）</span><input id="pw-price" type="number" min="0" step="0.01" placeholder="请输入目标价格"></label><div class="pw-actions"><button id="pw-reselect" class="pw-secondary">重新选择元素</button><button id="pw-save" class="pw-primary">保存监听</button></div>`;panel.querySelector(".pw-close").onclick=cleanup;panel.querySelector("#pw-reselect").onclick=()=>{const id=editingId;start(id)};panel.querySelector("#pw-save").onclick=save;panel.querySelector("#pw-price").focus()}
async function save(){const targetPrice=Number(panel.querySelector("#pw-price").value);if(!Number.isFinite(targetPrice)||targetPrice<0)return toast("请输入有效的目标价格");const result=await chrome.runtime.sendMessage({type:"SAVE_WATCH",watch:{id:editingId,title:panel.querySelector("#pw-title").value.trim()||document.title,url:location.href,selector:candidate.selector,sample:candidate.text,currentPrice:candidate.price,targetPrice,currency:candidate.currency}});if(result?.ok){cleanup();toast("监听已保存，将每小时自动检查")}}
function cleanup(){mode="idle";hovered=null;candidate=null;document.documentElement.classList.remove("pw-picking");document.removeEventListener("mousemove",onMove,true);document.removeEventListener("click",onPick,true);document.removeEventListener("keydown",onKey,true);highlight?.remove();panel?.remove();highlight=panel=null}
function onKey(e){if(e.key==="Escape")cleanup()}function toast(message){document.querySelector("#pw-toast")?.remove();const el=document.createElement("div");el.id="pw-toast";el.textContent=message;document.body.append(el);setTimeout(()=>el.remove(),2600)}
function cssPath(el){if(el.id&&/^[A-Za-z][\w-]*$/.test(el.id))return`#${CSS.escape(el.id)}`;const parts=[];while(el&&el.nodeType===1&&el!==document.body){let part=el.localName;const stable=[...el.classList].filter(c=>!/[0-9]{4,}|active|hover|selected/i.test(c)).slice(0,2);if(stable.length)part+=stable.map(c=>`.${CSS.escape(c)}`).join("");const siblings=el.parentElement?[...el.parentElement.children].filter(x=>x.localName===el.localName):[];if(siblings.length>1)part+=`:nth-of-type(${siblings.indexOf(el)+1})`;parts.unshift(part);el=el.parentElement;if(parts.length>=6)break}return parts.join(" > ")}
function parsePrice(t){const f=String(t).replace(/\s/g,"").match(/-?\d[\d.,]*/);if(!f)return NaN;let v=f[0],c=v.lastIndexOf(","),d=v.lastIndexOf(".");v=c>d?v.replace(/\./g,"").replace(",","."):v.replace(/,/g,"");return Number(v)}function detectCurrency(t){return t.match(/NZ\$|AU\$|US\$|CNY|RMB|[$€£¥￥]/i)?.[0]||""}function escapeHtml(t){return String(t).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}})();
