const list=document.querySelector("#list"),empty=document.querySelector("#empty"),refreshButton=document.querySelector("#refresh"),modal=document.querySelector("#modal"),search=document.querySelector("#search");let editingId=null,allWatches=[];
document.addEventListener("DOMContentLoaded",render);chrome.storage.onChanged.addListener(render);search.oninput=draw;
refreshButton.onclick=async()=>{refreshButton.disabled=true;refreshButton.textContent="正在刷新…";try{const result=await chrome.runtime.sendMessage({type:"REFRESH_ALL"});toast(result?.ok?"全部价格已更新":`有 ${result?.failed||1} 个商品更新失败，请查看商品提示`);await render()}catch{toast("刷新失败，请重新加载扩展后重试")}finally{refreshButton.disabled=false;refreshButton.textContent="↻ 全部刷新"}};
const addHelp=()=>alert("打开要跟踪的商品页面，点击浏览器工具栏中的价格跟踪图标，然后选择“添加价格跟踪”。");document.querySelector("#empty-add").onclick=addHelp;
async function render(){({watches:allWatches=[]}=await chrome.storage.local.get("watches"));document.querySelector("#subtitle").textContent=`共 ${allWatches.length} 个商品`;const newest=Math.max(0,...allWatches.map(w=>w.updatedAt||0));document.querySelector("#updated").textContent=newest?formatTime(newest):"—";draw()}
function draw(){const query=search.value.trim().toLowerCase(),watches=allWatches.filter(w=>`${w.title} ${safeDomain(w.url)}`.toLowerCase().includes(query));empty.hidden=!!watches.length||!!query;list.hidden=!watches.length;list.classList.toggle("sorting-disabled",!!query);list.replaceChildren(...watches.map(w=>card(w,!query)))}
function card(w,sortingEnabled){const article=document.createElement("article");article.className="item";article.dataset.id=w.id;article.innerHTML=`<button class="drag-handle" draggable="${sortingEnabled}" ${sortingEnabled?'title="拖动排序" aria-label="拖动商品排序"':'title="搜索时不能排序" aria-label="搜索时不能排序" disabled'}><span></span><span></span><span></span></button><a class="product" href="${esc(w.url)}" target="_blank" rel="noopener noreferrer"><span class="product-icon"><img class="site-icon" src="${esc(favicon(w.url))}" alt="网站图标"></span><div class="product-text"><div class="title-row"><h3 title="${esc(productTitle(w.title))}">${esc(productTitle(w.title))}</h3></div>${w.status==="error"?`<p class="error">更新失败：${esc(w.error||"未知错误")}</p>`:""}</div></a><div class="current-wrap">${w.triggered?'<span class="pill">已达目标</span>':""}<strong class="current">${esc(money(w))}</strong></div><label class="target-wrap"><input class="target-input" aria-label="目标价格" type="number" min="0" step="0.01" value="${Number(w.targetPrice)}"></label><div class="actions"><button class="icon-btn edit" title="重新选择价格区域" aria-label="重新选择价格区域"><img src="icon/edit.png" alt=""></button><button class="icon-btn update" title="刷新" aria-label="刷新价格"><img src="icon/ref.png" alt=""></button><button class="icon-btn danger delete" title="删除" aria-label="删除商品"><img src="icon/del.png" alt=""></button></div>`;
const handle=article.querySelector(".drag-handle");if(sortingEnabled){handle.ondragstart=e=>{article.classList.add("dragging");e.dataTransfer.effectAllowed="move";e.dataTransfer.setData("text/plain",String(w.id));e.dataTransfer.setDragImage(article,20,article.offsetHeight/2)};handle.ondragend=async()=>{article.classList.remove("dragging");list.querySelectorAll(".drag-over").forEach(el=>el.classList.remove("drag-over"));await saveListOrder()}}
article.querySelector(".edit").onclick=async e=>{const button=e.currentTarget;button.disabled=true;try{const result=await chrome.runtime.sendMessage({type:"EDIT_WATCH",id:w.id});if(!result?.ok)toast(result?.error||"无法打开商品页面")}catch{toast("无法打开商品页面，请重新加载扩展后重试")}finally{button.disabled=false}};article.querySelector(".target-input").onchange=async e=>{const value=Number(e.target.value);if(Number.isFinite(value)&&value>=0){await mutate(w.id,x=>{x.targetPrice=value;x.triggered=Number(x.currentPrice)<=value});toast("目标价格已保存")}};article.querySelector(".delete").onclick=()=>removeWithConfirm(w);article.querySelector(".update").onclick=async e=>{const button=e.currentTarget;button.disabled=true;try{const result=await chrome.runtime.sendMessage({type:"REFRESH_ONE",id:w.id});toast(result?.ok?"价格已刷新":"更新失败，请查看商品提示");await render()}catch{toast("刷新失败，请重新加载扩展后重试")}finally{button.disabled=false}};return article}
list.ondragover=e=>{const dragging=list.querySelector(".dragging"),target=e.target.closest(".item");if(!dragging||!target||target===dragging)return;e.preventDefault();e.dataTransfer.dropEffect="move";list.querySelectorAll(".drag-over").forEach(el=>el.classList.remove("drag-over"));target.classList.add("drag-over");const before=e.clientY<target.getBoundingClientRect().top+target.offsetHeight/2;list.insertBefore(dragging,before?target:target.nextSibling)};
list.ondrop=e=>{if(list.querySelector(".dragging"))e.preventDefault()};
async function saveListOrder(){const ids=[...list.querySelectorAll(".item")].map(el=>el.dataset.id),{watches=[]}=await chrome.storage.local.get("watches"),byId=new Map(watches.map(w=>[String(w.id),w])),ordered=ids.map(id=>byId.get(id)).filter(Boolean),known=new Set(ids);ordered.push(...watches.filter(w=>!known.has(String(w.id))));allWatches=ordered;await chrome.storage.local.set({watches:ordered});toast("商品顺序已保存")}
function openEdit(w){editingId=w.id;modal.hidden=false;document.querySelector("#preview-icon").textContent=initial(w);document.querySelector("#preview-title").textContent=w.title;document.querySelector("#preview-domain").textContent=safeDomain(w.url);document.querySelector("#preview-link").href=w.url;document.querySelector("#edit-title").value=w.title;document.querySelector("#edit-url").value=w.url;document.querySelector("#edit-current").value=money(w);document.querySelector("#edit-target").value=Number(w.targetPrice);document.querySelector("#edit-notify").checked=w.notify!==false}
function closeEdit(){modal.hidden=true;editingId=null}document.querySelectorAll(".close,.backdrop").forEach(el=>el.onclick=closeEdit);document.addEventListener("keydown",e=>{if(e.key==="Escape")closeEdit()});
document.querySelector("#edit-form").onsubmit=async e=>{e.preventDefault();await mutate(editingId,w=>{w.title=document.querySelector("#edit-title").value.trim();w.url=document.querySelector("#edit-url").value;w.targetPrice=Number(document.querySelector("#edit-target").value);w.notify=document.querySelector("#edit-notify").checked;w.triggered=Number(w.currentPrice)<=w.targetPrice});closeEdit();toast("商品信息已保存")};
document.querySelector("#modal-delete").onclick=async()=>{const w=allWatches.find(x=>x.id===editingId);if(w&&await removeWithConfirm(w))closeEdit()};
async function removeWithConfirm(w){if(!confirm(`删除“${w.title}”的跟踪？`))return false;await remove(w.id);toast("商品已删除");return true}async function mutate(id,fn){const{watches=[]}=await chrome.storage.local.get("watches"),w=watches.find(x=>x.id===id);if(w)fn(w);await chrome.storage.local.set({watches})}async function remove(id){const{watches=[]}=await chrome.storage.local.get("watches");await chrome.storage.local.set({watches:watches.filter(w=>w.id!==id)})}
function initial(w){return (w.title||safeDomain(w.url)||"P").trim()[0].toUpperCase()}function money(w){return Number.isFinite(Number(w.currentPrice))?`${Number(w.currentPrice).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`:"—"}function safeDomain(url){try{return new URL(url).hostname.replace(/^www\./,"")}catch{return url}}function formatTime(time){return time?new Intl.DateTimeFormat("zh-CN",{year:"numeric",month:"long",day:"numeric",hour:"2-digit",minute:"2-digit"}).format(time):"尚未更新"}function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}function toast(message){const el=document.querySelector("#toast");el.textContent=message;el.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.hidden=true,2200)}

function favicon(pageUrl){const site=new URL(pageUrl);if(site.hostname==="m1oils.co.nz"||site.hostname==="www.m1oils.co.nz")return "https://www.m1oils.co.nz/cdn/shop/files/Mobil_Lubricants_Logo_2024.png?v=1705440713&width=96";const url=new URL(chrome.runtime.getURL("/_favicon/"));url.searchParams.set("pageUrl",new URL(pageUrl).origin+"/");url.searchParams.set("size","32");return url.href}
function productTitle(title){return String(title??"").replace(/\s+[-\u2013\u2014|]\s*pak\s*[\u0027\u2019]?\s*n\s*[\u0027\u2019]?\s*save?\s*$/i, "").trim()}
